<?php

namespace AppBundle\Repository;

/**
 * CatalogueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatalogueRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllActive()
    {
        return $this->findBy(array('catalogue_active' => 1), array('catalogue_order' => 'asc'));
    }
    
    public function findOneByCatalogueName($name)
    {
        return $this->findOneBy(array('catalogue_active' => 1, 'catalogue_name' => $name));;
    }
}
