<?php

namespace AppBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOneByCategoryName($name)
    {
        return $this->findOneBy(array('category_active' => 1, 'category_name' => $name));
    }
}
