<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function find($id)
    {
        return $this->findOneBy(array('product_id' => $id, 'product_active' => 1));
    }
}
