<?php

namespace AppBundle\Repository;

/**
 * PurchaseItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PurchaseItemRepository extends \Doctrine\ORM\EntityRepository
{
}
