<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TextRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TextRepository extends EntityRepository
{
    public function findOneByTextName($name)
    {
        return $this->findOneBy(array('text_name' => $name));
    }
}
