services:
    cart:
        class: AppBundle\Lib\Cart
        arguments: ['@session']
    
    preference:
        class:     AppBundle\Lib\Preference
        arguments: ['@doctrine.orm.entity_manager']

    admin.text:
        class: AppBundle\Admin\TextAdmin
        arguments: [~, AppBundle\Entity\Text, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.text }
        calls:
            - [ setTemplate, [edit, AppBundle:Admin:edit.html.twig]]

    admin.article:
        class: AppBundle\Admin\ArticleAdmin
        arguments: [~, AppBundle\Entity\Article, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.article }
        calls:
            - [ setTemplate, [edit, AppBundle:Admin:edit.html.twig]]
    
    admin.brand:
        class: AppBundle\Admin\BrandAdmin
        arguments: [~, AppBundle\Entity\Brand, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.brand }

    admin.catalogue:
        class: AppBundle\Admin\CatalogueAdmin
        arguments: [~, AppBundle\Entity\Catalogue, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.catalogue }
        calls:
            - [ addChild, ['@admin.category'] ]
            - [ setTemplate, [edit, AppBundle:Admin:edit.html.twig]]

    admin.category:
        class: AppBundle\Admin\CategoryAdmin
        arguments: [~, AppBundle\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.category }
        calls:
            - [ addChild, ['@admin.product'] ]
            - [ setTemplate, [edit, AppBundle:Admin:edit.html.twig]]

    admin.product:
        class: AppBundle\Admin\ProductAdmin
        arguments: [~, AppBundle\Entity\Product, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.product }
        calls:
            - [ addChild, ['@admin.product_picture'] ]
            - [ setTemplate, [edit, AppBundle:Admin:edit.html.twig]]
            
    admin.product_picture:
        class: AppBundle\Admin\ProductPictureAdmin
        arguments: [~, AppBundle\Entity\ProductPicture, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.product_picture }

    admin.purchase:
        class: AppBundle\Admin\PurchaseAdmin
        arguments: [~, AppBundle\Entity\Purchase, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.purchase }
        calls:
            - [ addChild, ['@admin.purchase_item'] ]
            
    admin.purchase_item:
        class: AppBundle\Admin\PurchaseItemAdmin
        arguments: [~, AppBundle\Entity\PurchaseItem, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.purchase_item }

    admin.preference:
        class: AppBundle\Admin\PreferenceAdmin
        arguments: [~, AppBundle\Entity\Preference, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.preference }
