services:
    admin.text:
        class: AppBundle\Admin\TextAdmin
        arguments: [~, AppBundle\Entity\Text, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Тексты, group: Контент }
        calls:
            - [ setTemplate, [edit, AppBundle:Admin:edit.html.twig]]

    admin.article:
        class: AppBundle\Admin\ArticleAdmin
        arguments: [~, AppBundle\Entity\Article, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Статьи, group: Контент }
        calls:
            - [ setTemplate, [edit, AppBundle:Admin:edit.html.twig]]
    
    admin.brand:
        class: AppBundle\Admin\BrandAdmin
        arguments: [~, AppBundle\Entity\Brand, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Производители, group: Каталог }

    admin.catalogue:
        class: AppBundle\Admin\CatalogueAdmin
        arguments: [~, AppBundle\Entity\Catalogue, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Группы, group: Каталог }
        calls:
            - [ addChild, ['@admin.category'] ]
            - [ setTemplate, [edit, AppBundle:Admin:edit.html.twig]]

    admin.category:
        class: AppBundle\Admin\CategoryAdmin
        arguments: [~, AppBundle\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Категории, group: Каталог }
        calls:
            - [ addChild, ['@admin.product'] ]
            - [ setTemplate, [edit, AppBundle:Admin:edit.html.twig]]

    admin.product:
        class: AppBundle\Admin\ProductAdmin
        arguments: [~, AppBundle\Entity\Product, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Товары, group: Каталог }
        calls:
            - [ addChild, ['@admin.product_picture'] ]
            - [ setTemplate, [edit, AppBundle:Admin:edit.html.twig]]
            
    admin.product_picture:
        class: AppBundle\Admin\ProductPictureAdmin
        arguments: [~, AppBundle\Entity\ProductPicture, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Изображения, group: Каталог }

    admin.preference:
        class: AppBundle\Admin\PreferenceAdmin
        arguments: [~, AppBundle\Entity\Preference, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Настройки, group: Система }

